# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.2.6
_src_path: gh:algorandfoundation/algokit-python-template
author_email: iskysun96@gmail.com
author_name: Chris Kim (Hyunggun)
contract_name: hello_world
deployment_language: typescript
preset_name: starter
project_name: resource-population-examples-ts

